### ISSUE TITLE
Cannot get this project running

### ISSUE THREAD

**Issue by bradenpowers** [launchdarkly/hello-react-native#7]
I have tried to get this project running and I have run into several issues.  The first being that I had to remove the pods folder and reinstall the pods. The second issue that I am having is that there isn't a .jsbundle file.

**Comment by torchhound** [comment]
Hi @bradenpowers, thanks for reporting this issue. What commands are you running to bring this project up? What error did you encounter that you had to reinstall the pod dependencies? Is Xcode throwing an error for lack of .jsbundle or is it RN CLI?

**Comment by bradenpowers** [comment]
I ran react-native run-ios at first and it did compile and brought up the sim but I did get the .jsbundle error displayed in the sim.  I didn't run into any errors compiling the project after I removed the pod directory and ran pod install again.

**Comment by ClementPF** [comment]
@bradenpowers I had the same issue, and it was resolved by starting the bundler manually with
`npm run start`
Once the bundler is running you can go in Xcode and run the project (the .xcworkspace)

**Comment by bradenpowers** [comment]
I will try that out. Thanks!

**Comment by GERey** [comment]
Hi All! We updated the readme to include the pod install as well as the changes to the readme. Thanks for surfacing this!
